name: teste_flutter
description: "A new Flutter project."

# Prevenção contra publicação acidental no pub.dev
publish_to: 'none' # Remova essa linha caso deseje publicar no pub.dev

# Versão e número da build do seu aplicativo
version: 1.0.0+1

# Definição do ambiente para o SDK Flutter
environment:
  sdk: '>=3.4.4 <4.0.0'

# Dependências principais do projeto
dependencies:
  flutter:
    sdk: flutter

  # Pacote de ícones para iOS (Cupertino)
  cupertino_icons: ^1.0.6
  
  # Internacionalização
  intl: ^0.19.0
  
  # Gerenciamento de estado com Provider
  provider: ^6.1.2
  
  # Banco de dados SQLite
  sqflite: ^2.4.0
  
  # Formatação de texto com máscaras
  mask_text_input_formatter: ^2.9.0
  
  # Font Awesome Flutter (ícones de FontAwesome)
  font_awesome_flutter: ^10.8.0
  
  # Pacote de ícones vetoriais (flutter_vector_icons)
  flutter_vector_icons: ^2.0.0

# Dependências para desenvolvimento e testes
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints recomendados para boas práticas de codificação
  flutter_lints: ^5.0.0

# Seções específicas do Flutter

flutter:
  # Inclui o Material Icons (ícones padrão do Flutter)
  uses-material-design: true

  # Definição de assets (imagens) para o projeto
  assets:
    - assets/images/logo.png
    - assets/images/brazuca.png
    - assets/images/avatar.png

  # Definição de fontes customizadas utilizadas no projeto
  fonts:
    - family: Kodchasan
      fonts:
        - asset: assets/fonts/Kodchasan-Regular.ttf
        - asset: assets/fonts/Kodchasan-Bold.ttf
        - asset: assets/fonts/Kodchasan-ExtraLight.ttf
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-Thin.ttf
        - asset: assets/fonts/Kanit-Light.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
    - family: MontserratAlternates
      fonts:
        - asset: assets/fonts/MontserratAlternates-Regular.ttf

